# Generated by Django 4.2.17 on 2025-04-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("design_no", models.CharField(max_length=100)),
                ("job_no", models.CharField(max_length=100)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
