# Generated by Django 4.2.17 on 2025-06-03 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_id', models.CharField(max_length=50)),
                ('design_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('collection', models.CharField(blank=True, max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('producttype', models.CharField(max_length=100)),
                ('occation', models.CharField(blank=True, max_length=100)),
                ('gwt', models.DecimalField(max_digits=10, decimal_places=3)),
                ('nwt', models.DecimalField(max_digits=10, decimal_places=3)),
                ('dwt', models.DecimalField(max_digits=10, decimal_places=3)),
                ('dpcs', models.IntegerField()),
                ('swt', models.DecimalField(max_digits=10, decimal_places=3)),
                ('spcs', models.IntegerField()),
                ('miscwt', models.DecimalField(max_digits=10, decimal_places=3)),
                ('miscpcs', models.IntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('titleline', models.CharField(blank=True, max_length=255)),
                ('isNew', models.BooleanField(default=False)),
                ('length', models.CharField(blank=True, max_length=50)),
                ('width', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('margin', models.DecimalField(max_digits=8, decimal_places=2)),
                ('duty', models.DecimalField(max_digits=8, decimal_places=2)),
                ('totamt', models.DecimalField(max_digits=12, decimal_places=2)),
                ('vendor_code', models.CharField(blank=True, max_length=100)),
                ('parent_designno', models.CharField(blank=True, max_length=100)),
                ('package', models.CharField(blank=True, max_length=100)),
                ('stock_qty', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_design',
                'indexes': [
                    models.Index(fields=['design_no'], name='inventory_design_design_no_idx'),
                    models.Index(fields=['category'], name='inventory_design_category_idx'),
                    models.Index(fields=['is_active'], name='inventory_design_is_active_idx'),
                    models.Index(fields=['gender'], name='inventory_design_gender_idx'),
                    models.Index(fields=['collection'], name='inventory_design_collection_idx'),
                    models.Index(fields=['producttype'], name='inventory_design_producttype_idx'),
                    models.Index(fields=['subcategory'], name='inventory_design_subcategory_idx'),
                ],
            },
        ),
    ]
