# Generated by Django 4.2.17 on 2025-05-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="design_no",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
