# Generated by Django 4.2.17 on 2025-06-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_auto_20250602_2335"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InventoryDesign",
        ),
    ]
