# Generated by Django 4.2.17 on 2025-05-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0002_category_collection_gender_job_memorequest_product_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=50, unique=True)),
                ("design_no", models.CharField(max_length=50)),
                ("job_no", models.CharField(max_length=50)),
                ("metal_type", models.CharField(max_length=30)),
                ("metal_quality", models.CharField(max_length=30)),
                ("gwt", models.DecimalField(decimal_places=3, max_digits=10)),
                ("nwt", models.DecimalField(decimal_places=3, max_digits=10)),
                ("dwt", models.DecimalField(decimal_places=3, max_digits=10)),
                ("dpcs", models.IntegerField()),
                ("size", models.CharField(max_length=20)),
                ("memostock", models.BooleanField()),
                ("totamt", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name="job",
            name="product",
        ),
        migrations.RemoveField(
            model_name="memorequest",
            name="job",
        ),
        migrations.RemoveField(
            model_name="memorequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="product",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="subcategory",
        ),
        migrations.AlterUniqueTogether(
            name="productimage",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productview",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productview",
            name="user",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="category",
        ),
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="wishlistitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="wishlistitem",
            name="user",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Collection",
        ),
        migrations.DeleteModel(
            name="Gender",
        ),
        migrations.DeleteModel(
            name="Job",
        ),
        migrations.DeleteModel(
            name="MemoRequest",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.DeleteModel(
            name="ProductType",
        ),
        migrations.DeleteModel(
            name="ProductView",
        ),
        migrations.DeleteModel(
            name="Subcategory",
        ),
        migrations.DeleteModel(
            name="WishlistItem",
        ),
    ]
