# Generated by Django 4.2.17 on 2025-06-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_delete_inventorydesign"),
    ]

    operations = []
