# Generated by Django 4.2.17 on 2025-05-30 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0004_cart_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_no", models.CharField(max_length=50)),
                ("design_no", models.CharField(max_length=50)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "memo_requests",
            },
        ),
        migrations.AlterModelOptions(
            name="cart",
            options={},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="added_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="job_no",
            field=models.CharField(db_index=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("stock", "In Stock"),
                    ("memo", "Memo Request"),
                    ("custom", "Custom Order"),
                ],
                default="stock",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "job_no", "item_type")},
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["added_date"], name="cart_items_added_d_d316ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["job_no"], name="cart_items_job_no_5c26ff_idx"),
        ),
        migrations.AlterModelTable(
            name="cart",
            table="carts",
        ),
        migrations.AlterModelTable(
            name="cartitem",
            table="cart_items",
        ),
        migrations.AddField(
            model_name="memorequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memo_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="cart",
            name="date",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="job_number",
        ),
        migrations.AlterUniqueTogether(
            name="memorequest",
            unique_together={("user", "job_no")},
        ),
    ]
