# Generated by Django 4.2.17 on 2025-06-03 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_auto_20250602_2351"),
        ("inventory", "0004_create_design_table"),
    ]

    operations = []
