# Generated by Django 4.2.17 on 2025-06-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_merge_20250602_2352"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="design",
            new_name="inventory_design_design_no_idx",
            old_name="inv_des_dno_idx",
        ),
        migrations.RenameIndex(
            model_name="design",
            new_name="inventory_design_category_idx",
            old_name="inv_des_cat_idx",
        ),
        migrations.RenameIndex(
            model_name="design",
            new_name="inventory_design_is_active_idx",
            old_name="inv_des_act_idx",
        ),
        migrations.RenameIndex(
            model_name="design",
            new_name="inventory_design_gender_idx",
            old_name="inv_des_gen_idx",
        ),
        migrations.RenameIndex(
            model_name="design",
            new_name="inv_des_ptype_idx",
            old_name="inv_des_pt_idx",
        ),
        migrations.RenameIndex(
            model_name="design",
            new_name="inv_des_subcat_idx",
            old_name="inv_des_sub_idx",
        ),
    ]
