# Generated by Django 4.2.17 on 2025-05-31 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0005_memorequest_alter_cart_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="memorequest",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="memorequest",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="cart_items_added_d_d316ef_idx",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="cart_items_job_no_5c26ff_idx",
        ),
        migrations.RenameField(
            model_name="cartitem",
            old_name="added_at",
            new_name="date_added",
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="clarity",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="color",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="custom_order",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="custom_remarks",
            field=models.TextField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="dpcs",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="dwt",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="gwt",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="metal",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="on_memo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="cart_items/"),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product_sku",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="size",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="job_no",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product", "job_no")},
        ),
        migrations.AlterModelTable(
            name="cart",
            table=None,
        ),
        migrations.AlterModelTable(
            name="cartitem",
            table="inventory_cart_item",
        ),
        migrations.DeleteModel(
            name="MemoRequest",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="added_date",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="custom_data",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="design_no",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="inventory_item",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="item_type",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="subtotal",
        ),
    ]
