# Generated by Django 4.2.17 on 2025-05-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_memorequest_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="design_no",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="diamond_color",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="diamond_quality",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="item_status",
            field=models.CharField(default="pending", max_length=30),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="item_type",
            field=models.CharField(default="stock", max_length=20),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="metal_color",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="metal_quality",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="metal_type",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="nwt",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="custom_remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="dwt",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="gwt",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="job_no",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product_sku",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="size",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterModelTable(
            name="cartitem",
            table=None,
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="clarity",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="color",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="custom_order",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="dpcs",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="in_stock",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="metal",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="on_memo",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product_image",
        ),
    ]
