# Generated by Django 4.2.17 on 2025-05-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_ordergroup_requestorder_instockorder_customorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="design_no",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
