# Generated by Django 4.2.17 on 2025-05-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0007_alter_cartitem_unique_together_cartitem_design_no_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="date_added",
            new_name="added_at",
        ),
        migrations.RenameField(
            model_name="cartitem",
            old_name="quantity",
            new_name="pcs",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="custom_remarks",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="item_status",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product_id",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product_sku",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="total",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="unit_price",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="custom_remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="totamt",
            field=models.DecimalField(decimal_places=2, default="", max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="design_no",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="diamond_color",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="diamond_quality",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="dwt",
            field=models.DecimalField(decimal_places=3, default="", max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="gwt",
            field=models.DecimalField(decimal_places=3, default="", max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="item_type",
            field=models.CharField(
                choices=[("stock", "Stock"), ("memo", "Memo"), ("custom", "Custom")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="job_no",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="metal_color",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="metal_quality",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="metal_type",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="nwt",
            field=models.DecimalField(decimal_places=3, default="", max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="size",
            field=models.CharField(max_length=20),
        ),
    ]
