# Generated by Django 4.2.17 on 2025-05-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_design_design_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="design",
            name="design_no",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
