# Generated by Django 4.2.17 on 2025-05-16 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_design_design_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="design",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 5, 16, 0, 22, 12, 66179),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="design",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="design",
            name="image_base_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="design",
            name="last_synced",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="design",
            name="subcategory",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["design_no"], name="inventory_d_design__ed422d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["category"], name="inventory_d_categor_74e7a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["is_active"], name="inventory_d_is_acti_bbbd4b_idx"
            ),
        ),
    ]
