# Generated by Django 4.2.17 on 2025-05-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_product_supplier_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="collection",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="design",
            name="gender",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="design",
            name="product_type",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(fields=["gender"], name="inventory_d_gender_6ba370_idx"),
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["collection"], name="inventory_d_collect_b968cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["product_type"], name="inventory_d_product_f8dd6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["subcategory"], name="inventory_d_subcate_25a76e_idx"
            ),
        ),
    ]
