# Generated by Django 4.2.17 on 2025-05-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
