# Generated by Django 4.2.17 on 2025-05-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="admin_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default="ORD20250525211832", max_length=50, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_phone",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
