# Generated by Django 4.2.17 on 2025-05-25 21:22
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_admin_notes_order_cancelled_at_and_more"),
    ]

    operations = [
         # Add customer fields
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, default=''),
            preserve_default=False,
        ),
        # Add shipping cost field
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        # Add notes fields
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='internal_notes',
            field=models.TextField(blank=True, default='', help_text='Not visible to customers'),
        ),
        # Add tracking fields
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Add created_by field
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET_NULL,
                related_name='orders_created',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
