# Generated by Django 4.2.17 on 2025-05-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_add_missing_order_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="internal_notes",
            field=models.TextField(blank=True, help_text="Not visible to customers"),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
