# Generated by Django 4.2.17 on 2025-05-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_internal_notes_alter_order_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="custom_remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="design_no",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="diamond_color",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="diamond_quality",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="dwt",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="gwt",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("stock", "Stock Item"),
                    ("memo", "Memo Request"),
                    ("custom", "Custom Order"),
                ],
                default="stock",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="job_no",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="memo_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="memo_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="memo_return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="metal_color",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="metal_quality",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="metal_type",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="nwt",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_sku",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "item_type"], name="orders_orde_order_i_af7cd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["design_no", "job_no"], name="orders_orde_design__978775_idx"
            ),
        ),
    ]
