# Generated by Django 4.2.17 on 2025-05-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_number", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "order_sequence",
            },
        ),
    ]
